[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile"
watchPatterns = ["**/*"]

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 300
